version: '3.8'

services:
  db:
    image: postgres:alpine
    ports:
      - "2254:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dependencies
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    volumes:
      - ./data:/var/lib/postgresql/aperotech/data