DROP TABLE IF EXISTS PROJECT;
DROP TABLE IF EXISTS OBJECTIVE;

CREATE TABLE PROJECT
(
    id      INT AUTO_INCREMENT PRIMARY KEY,
    name    VARCHAR(255) NOT NULL,
    pom_url VARCHAR(255) NOT NULL
);

CREATE TABLE OBJECTIVE
(
    id      INT AUTO_INCREMENT PRIMARY KEY,
    group_id    VARCHAR(255) NOT NULL,
    artifact_id VARCHAR(255) NOT NULL,
    version VARCHAR(255) NOT NULL
);