DROP TABLE IF EXISTS PROJECT_DEPENDENCY;
DROP TABLE IF EXISTS PROJECT;
DROP TABLE IF EXISTS OBJECTIVE;
DROP TABLE IF EXISTS DEPENDENCY;

CREATE TABLE PROJECT
(
    id      INT AUTO_INCREMENT PRIMARY KEY,
    name    VARCHAR(255) UNIQUE NOT NULL,
    pom_url VARCHAR(255)        NOT NULL
);

CREATE TABLE OBJECTIVE
(
    id          INT AUTO_INCREMENT PRIMARY KEY,
    group_id    VARCHAR(255) NOT NULL,
    artifact_id VARCHAR(255) NOT NULL,
    version     VARCHAR(255) NOT NULL
);

CREATE TABLE DEPENDENCY
(
    id          INT AUTO_INCREMENT PRIMARY KEY,
    group_id    VARCHAR(255) NOT NULL,
    artifact_id VARCHAR(255) NOT NULL,
    version     VARCHAR(255) NOT NULL
);

CREATE TABLE PROJECT_DEPENDENCY
(
    project_id    INT,
    dependency_id INT,
    FOREIGN KEY (project_id) REFERENCES PROJECT (id),
    FOREIGN KEY (dependency_id) REFERENCES DEPENDENCY (id),
    PRIMARY KEY (project_id, dependency_id)
);