name: Build project

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: 'Build with Maven'
        run: mvn -B install --file pom.xml
      - name: 'Artifact: upload JaCoCo report'
        uses: actions/upload-artifact@v3
        with:
          name: jacoco
          path: '${{ github.workspace }}/target/jacoco/jacoco.xml'
          retention-days: 1

  codecov:
    needs: build
    name: codecov
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'Setup: checkout project'
        uses: actions/checkout@v3
      - name: 'Artifact: download JaCoCo report'
        uses: actions/download-artifact@v3
        with:
          name: jacoco
      - name: 'Codecov: sending JaCoCo analysis...'
        uses: codecov/codecov-action@v3
        with:
          files: jacoco.xml
          fail_ci_if_error: true
          verbose: true